[webservers]
web01 ansible_host=192.168.166.148

[dbservers]
db01 ansible_host=192.168.166.149

[all:children]
webservers
dbservers

[all:vars]
ansible_user=root
ansible_ssh_common_args=-o StrictHostKeyChecking=no
