- name: 部署 Nginx到 web服务器
  hosts: all
  tasks:
    - name: 安装 nginx
      yum:
        name: nginx
        state: present

    - name: 启动 nginx并设置开机自启动
      service:
        name: nginx
        state: started
        enabled: yes
